# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
main:
  - name: Home
    url: '#'
    weight: 10
  - name: Research
    url: research
    weight: 20
  - name: People
    url: '#'
    weight: 30
  - name: Professor
    url: people/professor/
    parent: People
    weight: 31
  - name: Researcher
    url: people/researcher/
    parent: People
    weight: 32
  - name: Projects
    url: event
    weight: 40
  - name: Publication
    url: publication
    weight: 50
  - name: News
    url: post
    weight: 60
  - name: Contact
    url: contact
    weight: 70
